#pragma once

#define GOOD_DATA_RATE "5Mbps"
#define GOOD_DELAY "10ms"
#define BAD_DATA_RATE "5Mbps"
#define BAD_DELAY "20ms"

#define MAX_FOLLOWING_LOSS 1

#define TCP_SOCKET_BASE_SACK_ENABLED true

// #define TCP_SOCKET_BASE_USE_NEW_DUPACK_LOGIC
// #define NS3_IDFEF_SACK_LOSS_CLASSIFICATION

#ifdef NS3_IDFEF_SACK_LOSS_CLASSIFICATION
#define TCP_SOCKET_BASE_USE_NEW_DUPACK_LOGIC
#endif
